services:
  # What to call the service hosting the site. Because there is only
  # one service, it is automatically set as the default service, which
  # does a few things
  #   1. Clones the git repository into the service container
  #   2. Exposes port 80 to the Tugboat HTTP proxy
  #   3. Routes requests to the preview URL to this service
  apache:
    # Use the available version of Apache by not specifying a version
    image: php:8.4-alpine

    # A set of commands to run while building this service
    commands:
      init:
        # Link the document root to the expected path
        - ln -snf "${TUGBOAT_ROOT}" "${DOCROOT}"
